use_frameworks!

target 'SocialLogin_Example' do
  pod 'SocialLogin', :path => '../'

  target 'SocialLogin_Tests' do
    inherit! :search_paths

    pod 'Quick', '~> 0.8'
  pod 'Nimble', '~> 3.0'
  pod 'FBSnapshotTestCase'
  pod 'Nimble-Snapshots'
  end
end
