use_frameworks!
  pod 'FoldingTabBar', :git => 'https://github.com/fel-cesar/FoldingTabBar.iOS.git' , :commit => '9809b69'
target 'SocialLogin_Example' do
  pod 'SocialLogin', :path => '../'

  target 'SocialLogin_Tests' do
    inherit! :search_paths

    pod 'Quick', '~> 0.8'
  pod 'Nimble', '~> 3.0'
  pod 'FBSnapshotTestCase'
  pod 'Nimble-Snapshots'
  end
end
